### ISSUE TITLE
Features to Add

### ISSUE THREAD

**Issue by CallumRyan** [PixelogicDev/TwitchFestify#1]
# Some Features to Add

## Currently Playing
Ability to see the song **Currently Playing**
* Should have the cover image of the track
* Should have the current progress of the song

## Polling
Ability to poll all users currently watching the stream to change song
Should probably have the button next to the Currently Playing

## Current Track List
* Ability to see the current track list
* Ability to search and add/remove votes to songs
* Admin(Creator) Ability to have "blocked" lists where you can ban certain songs/artists

## Stretch features to add
Subscriber only mode - not sure of exact use | Possibly for larger creators?
Bit integration for ability to choose next immediate song - Goes to Creator
List of most popular song requests
Panel Version (Underneath Stream)

**Comment by adilanchian** [comment]
These are awesome @CallumRyan ! Thanks for adding these. Here are my thoughts:

I think we should break these out into separate issues and get a base extension project up and running here. 

Another thing is we should checkout the Festify Repo, fork it, and get it running locally and see what that entails. (located here: https://github.com/Festify/app)

I think these are great features to start with a V1. I will be updating the README with some logistics on adding your code into the repo and such :)

**Comment by CallumRyan** [comment]
Will break them out into separate issues
Good idea :ok_hand:
