### ISSUE TITLE
Getting Started: Setup Festify backend locally

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/TwitchFestify#8]
I think before we begin anything we need to go ahead and get our local env setup for development with Festify. I'm going to see if I can get this going in the next couple hours.

**Comment by adilanchian** [comment]
Alright I have Festify almost fully running locally. Having some auth issues with Spotify. At the end of the day, I think we just need the Firebase functions. The rest of the project is for the client. 

While we can utilize this to build out our extension, the biggest thing is to have Festify's hosting setup

**Comment by isabellabrookes** [comment]
So are we planning to run our own instance of festify? 
More deets, plz.

**Comment by adilanchian** [comment]
@isabellabrookes - hiya! Ya good question... 

So I haven't been able to get a look at this in the last 10 days unfortunately, but this was my thought process:

1. We utilize Festify's open source repo to get a quick backend setup of almost everything we want (voting, login with Spotify, playing songs, the works). 
2. We rip out the client portion of it as I'm assuming we will go with a more custom solution for this.
3. With the backend setup and deployed to Firebase (They use a lot of Firebase functions) we can all hit it during the dev process. Essentially, we can have another instance for when we release

Does this give a bit more clarity? The backend of Festify requires a good amount of tokens and accounts to be created, so if you do end up getting this up before I do, I can DM you the token's I have created on Discord for this if thats cool?

**Comment by adilanchian** [comment]
There have been multiple talks about this... I think I really wanted to put together a platform that utilized Festify, but it seems like it might be a better scenario if we can setup our own backend for this! With that being said, I am going to close out this issue and create a new one.
